import TokenType.*
import scala.collection.mutable.ListBuffer

// Step 3: turn the AST into a synthesizable Verilog module for the Manhattan
// Reasoning FPGA cloud, plus the matching Python client.
//
// Calling convention (v1 — straight-line, pure combinational):
//   var x;            -> host-writable INPUT register  (host: app.write)
//   var y = expr;     -> COMPUTED hardware, host-readable
//   return expr;      -> mirrored into a RESULT register, host-readable
//
// The generated module is a Wishbone B4 slave named `top`, exactly the port
// shape the platform expects (see the echo_slave example). `wb_adr` is a WORD
// address; the Python SDK passes byte offsets, which it shifts down by 2.

case class RegInfo(name: String, byteOffset: Int, dir: String) // dir = "in" | "out"

case class Generated(verilog: String, python: String, regs: List[RegInfo])

object VerilogCodegen:
  private val InputBase  = 0x10 // byte offset of first input register
  private val OutputBase = 0x40 // byte offset of first computed/output register

  def generate(statements: List[Stmt], appName: String = "mini_dsl"): Generated =
    // 1. Classify top-level declarations.
    val inputs   = ListBuffer.empty[String]            // uninitialized vars
    val computed = ListBuffer.empty[(String, Expr)]    // var = expr
    var returnExpr: Option[Expr] = None

    statements.foreach {
      case Stmt.VarDecl(name, None)        => inputs += name.lexeme
      case Stmt.VarDecl(name, Some(init))  => computed += (name.lexeme -> init)
      case Stmt.Return(_, value)           => returnExpr = value
      case _                               => () // print/if/while ignored in v1
    }

    // 2. Assign register addresses (byte offsets, like the SDK examples).
    val inRegs  = inputs.zipWithIndex.map((n, i) => n -> (InputBase + i * 4)).toMap
    val outVars = computed.map(_._1)
    val outRegs = outVars.zipWithIndex.map((n, j) => n -> (OutputBase + j * 4)).toMap
    val resultOffset = OutputBase + outVars.size * 4

    // Symbol table: DSL var name -> Verilog signal name.
    def signal(name: String): String =
      if inRegs.contains(name) then s"in_$name" else name

    // 3. Emit a Verilog expression from an AST expression.
    def emit(e: Expr): String = e match
      case Expr.Literal(v)        => literal(v)
      case Expr.Variable(t)       => signal(t.lexeme)
      case Expr.Grouping(inner)   => s"(${emit(inner)})"
      case Expr.Unary(op, r)      => op.tokenType match
        case MINUS => s"(-${emit(r)})"
        case BANG  => s"(!${emit(r)})"
        case other => sys.error(s"Unsupported unary op $other")
      case Expr.Binary(l, op, r)  => s"(${emit(l)} ${binOp(op)} ${emit(r)})"
      case Expr.Logical(l, op, r) =>
        val o = if op.tokenType == AND then "&&" else "||"
        s"(${emit(l)} $o ${emit(r)})"
      case Expr.Assign(_, _)      => sys.error("Assignment not supported in v1 codegen")

    // 4. Build the Verilog module.
    val v = StringBuilder()
    v ++= s"// Auto-generated by mini-dsl-scala. App: $appName\n"
    v ++= "module top (\n"
    v ++= "  input  wire        clk, rst,\n"
    v ++= "  input  wire        wb_cyc, wb_stb, wb_we,\n"
    v ++= "  input  wire [8:0]  wb_adr,\n"
    v ++= "  input  wire [31:0] wb_dat_w,\n"
    v ++= "  input  wire [3:0]  wb_sel,\n"
    v ++= "  output reg  [31:0] wb_dat_r,\n"
    v ++= "  output reg         wb_ack\n"
    v ++= ");\n\n"

    // Input registers (host-writable via Wishbone).
    inputs.foreach(n => v ++= s"  reg [31:0] in_$n;\n")
    if inputs.nonEmpty then v ++= "\n"

    // Computed values + result as combinational wires.
    computed.foreach((n, _) => v ++= s"  wire [31:0] $n;\n")
    v ++= "  wire [31:0] result;\n\n"
    computed.foreach((n, init) => v ++= s"  assign $n = ${emit(init)};\n")
    v ++= s"  assign result = ${returnExpr.map(emit).getOrElse("32'h0")};\n\n"

    // Wishbone slave: registered single-cycle ack, write to input regs, read mux.
    v ++= "  always @(posedge clk) begin\n"
    v ++= "    if (rst) begin\n"
    v ++= "      wb_ack   <= 1'b0;\n"
    v ++= "      wb_dat_r <= 32'h0;\n"
    inputs.foreach(n => v ++= s"      in_$n <= 32'h0;\n")
    v ++= "    end else begin\n"
    v ++= "      wb_ack <= wb_cyc & wb_stb & ~wb_ack;\n"
    // writes
    if inputs.nonEmpty then
      v ++= "      if (wb_cyc & wb_stb & wb_we & ~wb_ack) begin\n"
      v ++= "        case (wb_adr)\n"
      inputs.foreach(n =>
        v ++= f"          9'd${inRegs(n) >> 2}%-3s: in_$n <= wb_dat_w;\n")
      v ++= "          default: ;\n"
      v ++= "        endcase\n"
      v ++= "      end\n"
    // reads
    v ++= "      if (wb_cyc & wb_stb & ~wb_we & ~wb_ack) begin\n"
    v ++= "        case (wb_adr)\n"
    computed.foreach((n, _) =>
      v ++= f"          9'd${outRegs(n) >> 2}%-3s: wb_dat_r <= $n;\n")
    v ++= f"          9'd${resultOffset >> 2}%-3s: wb_dat_r <= result;\n"
    v ++= "          default: wb_dat_r <= 32'h0;\n"
    v ++= "        endcase\n"
    v ++= "      end\n"
    v ++= "    end\n"
    v ++= "  end\n"
    v ++= "endmodule\n"

    // 5. Build the matching Python client.
    val regList =
      inputs.map(n => RegInfo(n, inRegs(n), "in")).toList ++
      outVars.map(n => RegInfo(n, outRegs(n), "out")).toList :+
      RegInfo("result", resultOffset, "out")

    val p = StringBuilder()
    p ++= "import manhattan_reasoning_gym as mrg\n\n"
    p ++= "class Regs(mrg.cloud.RegisterMap):\n"
    regList.foreach(r => p ++= f"    ${r.name.toUpperCase}%-8s = 0x${r.byteOffset}%04X  # ${r.dir}\n")
    p ++= "\n"
    p ++= s"""app = mrg.cloud.App("$appName", design="design.v", registers=Regs)\n\n"""
    p ++= "@app.local_entrypoint()\n"
    p ++= "def main():\n"
    if inputs.isEmpty then p ++= "    # (no inputs — this design has no host-writable registers)\n"
    inputs.zipWithIndex.foreach((n, i) =>
      p ++= f"    app.write(Regs.${n.toUpperCase}, ${i + 1})  # TODO: real input value\n")
    outVars.foreach(n =>
      p ++= s"""    print("$n =", app.read(Regs.${n.toUpperCase}))\n""")
    p ++= s"""    print("result =", app.read(Regs.RESULT))\n"""

    Generated(v.toString, p.toString, regList)

  // ---- helpers ----

  private def literal(v: Any): String = v match
    case d: Double  => (d.toLong & 0xFFFFFFFFL).toString      // 32-bit integer
    case b: Boolean => if b then "32'h1" else "32'h0"
    case null       => "32'h0"
    case other      => sys.error(s"Unsupported literal in hardware: $other")

  private def binOp(op: Token): String = op.tokenType match
    case PLUS          => "+"
    case MINUS         => "-"
    case STAR          => "*"
    case SLASH         => "/"
    case GREATER       => ">"
    case GREATER_EQUAL => ">="
    case LESS          => "<"
    case LESS_EQUAL    => "<="
    case EQUAL_EQUAL   => "=="
    case BANG_EQUAL    => "!="
    case other         => sys.error(s"Unsupported binary op $other")
